### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [SetOfAllSets/simply-perfect-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by SetOfAllSets** [comment]
![image](https://user-images.githubusercontent.com/98566029/215360686-f1bac962-efce-4c4d-94b4-daf6a1179b0e.png)

**Comment by SetOfAllSets** [comment]
![image](https://user-images.githubusercontent.com/98566029/215363766-d3f3185b-2fa8-4e2b-8802-46c98838d05a.png)
